
# .travis.yaml
#
# This file is part of NEST.
#
# Copyright (C) 2004 The NEST Initiative
#
# NEST is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# NEST is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NEST.  If not, see <http://www.gnu.org/licenses/>.

#services:
#  - docker
#
#addons:
#  apt:
#    packages:
#      - docker-ce
#
#before_install:
#  - bash extras/docker_run.sh
#
#script:
#  - docker images

language: python

services:
  - docker

stages:
  - test

env:
  - xMPI=1
  - xMPI=0

jobs:
  include:
  - stage: test
    before_script: docker pull steffengraber/travis-nest:latest
    script:
    - docker run -it -d --rm --user nest --name travis-test-nest -v $(pwd):/home/nest/data steffengraber/travis-nest:latest
    - docker ps -a
    - docker exec -e xMPI=$xMPI --user nest travis-test-nest bash /home/nest/data/extras/travis_tests.sh


notifications:
  email:
    recipients:
      - s.graber@fz-juelich.de
    on_success: always
    on_failure: always