
# .travis.yaml
#
# This file is part of NEST.
#
# Copyright (C) 2004 The NEST Initiative
#
# NEST is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# NEST is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NEST.  If not, see <http://www.gnu.org/licenses/>.

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
- docker pull steffengraber/travis-nest:latest
- docker run -it --rm -d --user nest --name travis-test-nest -v $(pwd):/home/nest/data steffengraber/travis-nest:latest
- docker images
- docker container exec -it --env "xMPI=1" --env "xPYTHON=0" --user nest travis-test-nest sh /home/nest/data/extras/travis_tests.sh
- docker container exec -it --env "xMPI=0" --env "xPYTHON=1" --user nest travis-test-nest sh  /home/nest/data/extras/travis_tests.sh
- docker ps -a

script: docker ps -a

