name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        on:
          push:
            branches: nest-wheel
        uses: steffengraber/nest-simulator
        # to supply options, put them in 'env', like:
        env:
          NEST_INSTALL_NODOC: 1

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
